#!/bin/sh

list_users () {
	who -u | cut -d' ' -f1 | uniq
}

remove () {
	[ -d /etc/sv/"$1" ] && rm -rf /etc/sv/"$1"
}

create () {
	[ -d /etc/sv/"$1" ] || cp -r /etc/sv/user-session /etc/sv/"$1"
}

disable () {
	[ -h /var/service/"$1" ] && rm /var/service/"$1"
}

enable () {
	[ -h /var/service/"$1" ] || ln -s /etc/sv/"$1" /var/service/"$1"
}

stop () {
	sv status "$1" && sv stop "$1"
}

start () {
	sv status "$1" || sv start "$1"
}

create_session () {
	create "$1" && enable "$1" && start "$1"
}

remove_session () {
	stop "$1"; disable "$1"; remove "$1"
}

list_sessions () {
	for SERVICE in $(find /etc/sv -name "user.*"); do
		echo "$(basename $SERVICE)"
	done
}

create_sessions () {
	for user in $(who -u | cut -d' ' -f1 | uniq); do
		local SERVICE="user.$user"
		create_session "$SERVICE"
	done
}

remove_sessions () {
	for SERVICE in $(list_sessions); do
		remove_session "$SERVICE"	
	done
}

remove_gone () {
	for SERVICE in $(list_sessions); do
		local USER="${SERVICE##*.}"
		list_users | grep -vq "^$USER" && remove_session "$SERVICE"
	done
}

watch_sessions () {
	while true; do
		create_sessions && remove_gone && sleep 3
	done
}

case "$1" in
	watch)
		watch_sessions
		;;
	list)
		list_sessions
		;;
	create)
		case "$2" in
			all)
				create_sessions
				;;
			*)
				[ -z "$2" ] || create_session "$2"
				;;
		esac
		;;
	remove)
		case "$2" in
			all)
				remove_sessions
				;;
			*)
				[ -z "$2" ] || remove_session "$2"
				;;
		esac
		;;
esac

